title: Maryum Mateen
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maryummateen.com" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Maryum Mateen'
  last_name: 'Mateen'
  cv: ''
  #avatar: '/images/avatar.jpeg'
  github_username:  mmateen19  
  email: maryummateen19@gmail.com
  #vk_id: id201664979
  #telegram_name: vikapitoshka 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html

